"""add trips table and checklist trip_id/favorite

Revision ID: b4d291416b43
Revises: 171e2eaebdfb
Create Date: 2026-07-20 21:23:47.162843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4d291416b43'
down_revision = '171e2eaebdfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trips',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trip_name', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('checklists', schema=None) as batch_op:
        # trip_id starts nullable so existing rows survive the ADD COLUMN;
        # it's backfilled below and tightened to NOT NULL afterward.
        batch_op.add_column(sa.Column('trip_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('favorite', sa.Boolean(), server_default='false', nullable=False))
        batch_op.create_foreign_key(None, 'trips', ['trip_id'], ['id'])

    # ### end Alembic commands ###

    # --- data migration: give every user with pre-existing checklists a
    # default trip, and point those checklists at it, before trip_id can be
    # made required ---
    bind = op.get_bind()
    trips_table = sa.table(
        'trips',
        sa.column('id', sa.Integer),
        sa.column('trip_name', sa.String),
        sa.column('user_id', sa.Integer),
    )
    checklists_table = sa.table(
        'checklists',
        sa.column('id', sa.Integer),
        sa.column('user_id', sa.Integer),
        sa.column('trip_id', sa.Integer),
    )

    orphan_user_ids = bind.execute(
        sa.text('SELECT DISTINCT user_id FROM checklists WHERE trip_id IS NULL')
    ).scalars().all()

    for user_id in orphan_user_ids:
        result = bind.execute(
            trips_table.insert()
            .values(trip_name='My Trips', user_id=user_id)
            .returning(trips_table.c.id)
        )
        default_trip_id = result.scalar_one()
        bind.execute(
            checklists_table.update()
            .where(checklists_table.c.user_id == user_id)
            .where(checklists_table.c.trip_id.is_(None))
            .values(trip_id=default_trip_id)
        )

    with op.batch_alter_table('checklists', schema=None) as batch_op:
        batch_op.alter_column('trip_id', existing_type=sa.Integer(), nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checklists', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('favorite')
        batch_op.drop_column('trip_id')

    op.drop_table('trips')
    # ### end Alembic commands ###
